### ISSUE TITLE
Error in log?

### ISSUE THREAD

**Issue by originalfoo** [kianzarrin/NodeController#14]
Not sure if this is error or just unusual use of stack trace.

```diff
TRANSPILER CalculateCornerPatch: Successfully patched NetSegment.CalculateCorner(). found 5 instances of Ldfld NetInfo.m_minCornerOffset
NodeControllerTool.Create()
GetPanel returns RoadsOptionPanel(PublicTransportPanel) (ColossalFramework.UI.UIPanel)
- NodeControllerButton.Awake() is called.   at System.Environment.get_StackTrace()

   at NodeController.GUI.NodeControllerButton.Awake()

   at UnityEngine.GameObject.Internal_AddComponentWithType(System.Type )

   at UnityEngine.GameObject.AddComponent(System.Type componentType)

   at UnityEngine.GameObject.AddComponent()

   at ColossalFramework.UI.UIComponent.AddUIComponent()

   at NodeController.GUI.NodeControllerButton.CreateButton()

   at NodeController.Tool.NodeControllerTool.Awake()

   at UnityEngine.GameObject.Internal_AddComponentWithType(System.Type )

   at UnityEngine.GameObject.AddComponent(System.Type componentType)

   at UnityEngine.GameObject.AddComponent()

   at NodeController.Tool.NodeControllerTool.Create()

   at NodeController.LifeCycle.LifeCycle.Load()

   at NodeController.LifeCycle.LoadingExtention.OnLevelLoaded(LoadMode mode)

   at LoadingWrapper.DMD<DMD<OnLevelLoaded_Patch3>?-1958036864::OnLevelLoaded_Patch3>(.LoadingWrapper , UpdateMode )

   at LoadingManager+<LoadLevelComplete>c__Iterator9.MoveNext()

   at LoadingManager.Update()
NodeControllerTool.OnEnable
Null
NodeData.Refresh() Updating node:97
NodeData.Refresh() Updating node:267
NodeData.Refresh() Updating node:1874
NodeData.Refresh() Updating node:4537
NodeData.Refresh() Updating node:5258
NodeData.Refresh() Updating node:5509
NodeData.Refresh() Updating node:5803
NodeData.Refresh() Updating node:6476
NodeData.Refresh() Updating node:8680
NodeData.Refresh() Updating node:12187
NodeData.Refresh() Updating node:14405
NodeData.Refresh() Updating node:19352
NodeData.Refresh() Updating node:19744
NodeData.Refresh() Updating node:24787
NodeData.Refresh() Updating node:27311
NodeData.Refresh() Updating node:28161
NodeData.Refresh() Updating node:29268
NodeData.Refresh() Updating node:30742
ReplaceCalls start

// load of transpiler stuff

NodeControllerTool.OnDisable
```

* [output_log.txt](https://github.com/kianzarrin/NodeController/files/4739269/output_log.txt)
* [NodeController.log](https://github.com/kianzarrin/NodeController/files/4739272/NodeController.log)
* [RMCrosswalks.debug.log](https://github.com/kianzarrin/NodeController/files/4739273/RMCrosswalks.debug.log)
* [SequenceLogger.log](https://github.com/kianzarrin/NodeController/files/4739274/SequenceLogger.log)
* [TMPE.log](https://github.com/kianzarrin/NodeController/files/4739275/TMPE.log)
* [AutoRepair.log](https://github.com/kianzarrin/NodeController/files/4739276/AutoRepair.log)
* [DuplicateAssemblyScanner.log](https://github.com/kianzarrin/NodeController/files/4739277/DuplicateAssemblyScanner.log)
* [HideUnconnectedTracks.debug.log](https://github.com/kianzarrin/NodeController/files/4739278/HideUnconnectedTracks.debug.log)

**Comment by kianzarrin** [comment]
sorry didn't notice this. just usual stack trace. no error. its is alpha debug version after all. I want to know what people were doing when they are filing complaints.
